# render.yaml
static_sites:
  - name: lennas-portfolio
    build_command: echo "Static site - no build needed"
    static_path: .
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    headers:
      - path: "/sitemap.xml"
        name: "Content-Type"
        value: "application/xml"
      - path: "/robots.txt"
        name: "Content-Type"
        value: "text/plain"
